/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/BaseHeader.vue')['default']
    BaseMenu: typeof import('./components/BaseMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IAntDesignStockOutlined: typeof import('~icons/ant-design/stock-outlined')['default']
    IBxBxsCircleQuarter: typeof import('~icons/bx/bxs-circle-quarter')['default']
    IBxBxsCircleThreeQuarter: typeof import('~icons/bx/bxs-circle-three-quarter')['default']
    IIcBaselineCheckCircle: typeof import('~icons/ic/baseline-check-circle')['default']
    IIcSharpCircle: typeof import('~icons/ic/sharp-circle')['default']
    IMaterialSymbolsDrafts: typeof import('~icons/material-symbols/drafts')['default']
    IMaterialSymbolsPerson: typeof import('~icons/material-symbols/person')['default']
    IMaterialSymbolsPersonRaisedHand: typeof import('~icons/material-symbols/person-raised-hand')['default']
    IMaterialSymbolsPsychologyAltOutline: typeof import('~icons/material-symbols/psychology-alt-outline')['default']
    IMaterialSymbolsSheets: typeof import('~icons/material-symbols/sheets')['default']
    IMdiMoonFirstQuarter: typeof import('~icons/mdi/moon-first-quarter')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseDark: typeof import('@vueuse/components')['UseDark']
  }
}
